# site settings
title: Hello
subtitle: Michael Schmitz
email: mail@michaelschmitz.me
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: San Diego
state: CA
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/misterschmitz
gitlab_url:
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/mschmitz1
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
